# Generated by Django 5.1.1 on 2024-10-26 02:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_interes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupointeres',
            name='verificado',
        ),
        migrations.AddField(
            model_name='grupointeres',
            name='image',
            field=models.ImageField(blank=True, default='image_grupo_interes/def.png', null=True, upload_to='image_grupo_interes/'),
        ),
        migrations.AlterField(
            model_name='grupointeres',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grupointeres',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos_interes', to=settings.AUTH_USER_MODEL),
        ),
    ]
