# Generated by Django 5.1.1 on 2024-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_interes', '0002_remove_grupointeres_verificado_grupointeres_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='grupos_interes', to='grupos_interes.comentario'),
        ),
    ]
