# Generated by Django 5.1.1 on 2024-10-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_interes', '0003_remove_comentario_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupointeres',
            name='embeddings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
