# Generated by Django 5.1.1 on 2024-09-16 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('indicativo_pais', models.CharField(choices=[('+93', 'Afganistán'), ('+355', 'Albania'), ('+49', 'Alemania'), ('+376', 'Andorra'), ('+244', 'Angola'), ('+1-268', 'Antigua y Barbuda'), ('+966', 'Arabia Saudita'), ('+213', 'Argelia'), ('+54', 'Argentina'), ('+374', 'Armenia'), ('+61', 'Australia'), ('+43', 'Austria'), ('+994', 'Azerbaiyán'), ('+1-242', 'Bahamas'), ('+973', 'Baréin'), ('+880', 'Bangladés'), ('+1-246', 'Barbados'), ('+32', 'Bélgica'), ('+501', 'Belice'), ('+229', 'Benín'), ('+975', 'Bhután'), ('+375', 'Bielorrusia'), ('+95', 'Birmania (Myanmar)'), ('+591', 'Bolivia'), ('+387', 'Bosnia y Herzegovina'), ('+267', 'Botsuana'), ('+55', 'Brasil'), ('+673', 'Brunéi'), ('+359', 'Bulgaria'), ('+226', 'Burkina Faso'), ('+257', 'Burundi'), ('+238', 'Cabo Verde'), ('+855', 'Camboya'), ('+237', 'Camerún'), ('+1', 'Canadá | Estados Unidos'), ('+974', 'Catar'), ('+235', 'Chad'), ('+56', 'Chile'), ('+86', 'China'), ('+357', 'Chipre'), ('+57', 'Colombia'), ('+269', 'Comoras'), ('+850', 'Corea del Norte'), ('+82', 'Corea del Sur'), ('+225', 'Costa de Marfil'), ('+506', 'Costa Rica'), ('+385', 'Croacia'), ('+53', 'Cuba'), ('+45', 'Dinamarca'), ('+1-767', 'Dominica'), ('+593', 'Ecuador'), ('+20', 'Egipto'), ('+503', 'El Salvador'), ('+971', 'Emiratos Árabes Unidos'), ('+291', 'Eritrea'), ('+421', 'Eslovaquia'), ('+386', 'Eslovenia'), ('+34', 'España'), ('+372', 'Estonia'), ('+251', 'Etiopía'), ('+63', 'Filipinas'), ('+358', 'Finlandia'), ('+679', 'Fiyi'), ('+33', 'Francia'), ('+241', 'Gabón'), ('+220', 'Gambia'), ('+995', 'Georgia'), ('+233', 'Ghana'), ('+1-473', 'Granada'), ('+30', 'Grecia'), ('+502', 'Guatemala'), ('+224', 'Guinea'), ('+245', 'Guinea-Bisáu'), ('+240', 'Guinea Ecuatorial'), ('+592', 'Guyana'), ('+509', 'Haití'), ('+504', 'Honduras'), ('+36', 'Hungría'), ('+91', 'India'), ('+62', 'Indonesia'), ('+964', 'Irak'), ('+98', 'Irán'), ('+353', 'Irlanda'), ('+354', 'Islandia'), ('+972', 'Israel'), ('+39', 'Italia'), ('+1-876', 'Jamaica'), ('+81', 'Japón'), ('+962', 'Jordania'), ('+254', 'Kenia'), ('+996', 'Kirguistán'), ('+686', 'Kiribati'), ('+965', 'Kuwait'), ('+856', 'Laos'), ('+371', 'Letonia'), ('+961', 'Líbano'), ('+266', 'Lesoto'), ('+231', 'Liberia'), ('+218', 'Libia'), ('+423', 'Liechtenstein'), ('+370', 'Lituania'), ('+352', 'Luxemburgo'), ('+389', 'Macedonia del Norte'), ('+261', 'Madagascar'), ('+60', 'Malasia'), ('+265', 'Malawi'), ('+960', 'Maldivas'), ('+223', 'Malí'), ('+356', 'Malta'), ('+212', 'Marruecos'), ('+230', 'Mauricio'), ('+222', 'Mauritania'), ('+52', 'México'), ('+691', 'Micronesia'), ('+373', 'Moldavia'), ('+377', 'Mónaco'), ('+976', 'Mongolia'), ('+382', 'Montenegro'), ('+258', 'Mozambique'), ('+264', 'Namibia'), ('+674', 'Nauru'), ('+977', 'Nepal'), ('+505', 'Nicaragua'), ('+227', 'Níger'), ('+234', 'Nigeria'), ('+47', 'Noruega'), ('+64', 'Nueva Zelanda'), ('+968', 'Omán'), ('+31', 'Países Bajos'), ('+92', 'Pakistán'), ('+680', 'Palaos'), ('+507', 'Panamá'), ('+675', 'Papúa Nueva Guinea'), ('+595', 'Paraguay'), ('+51', 'Perú'), ('+48', 'Polonia'), ('+351', 'Portugal'), ('+44', 'Reino Unido'), ('+236', 'República Centroafricana'), ('+420', 'República Checa'), ('+1-809, +1-829, +1-849', 'República Dominicana'), ('+242', 'República del Congo'), ('+250', 'Ruanda'), ('+40', 'Rumania'), ('+7', 'Rusia | Kazajistán'), ('+685', 'Samoa'), ('+1-869', 'San Cristóbal y Nieves'), ('+378', 'San Marino'), ('+1-784', 'San Vicente y las Granadinas'), ('+1-758', 'Santa Lucía'), ('+239', 'Santo Tomé y Príncipe'), ('+221', 'Senegal'), ('+381', 'Serbia'), ('+248', 'Seychelles'), ('+232', 'Sierra Leona'), ('+65', 'Singapur'), ('+963', 'Siria'), ('+252', 'Somalia'), ('+94', 'Sri Lanka'), ('+268', 'Suazilandia'), ('+249', 'Sudán'), ('+27', 'Sudáfrica'), ('+46', 'Suecia'), ('+41', 'Suiza'), ('+597', 'Surinam'), ('+66', 'Tailandia'), ('+255', 'Tanzania'), ('+992', 'Tayikistán'), ('+670', 'Timor Oriental'), ('+228', 'Togo'), ('+676', 'Tonga'), ('+1-868', 'Trinidad y Tobago'), ('+216', 'Túnez'), ('+993', 'Turkmenistán'), ('+90', 'Turquía'), ('+688', 'Tuvalu'), ('+380', 'Ucrania'), ('+256', 'Uganda'), ('+598', 'Uruguay'), ('+998', 'Uzbekistán'), ('+678', 'Vanuatu'), ('+379', 'Vaticano'), ('+58', 'Venezuela'), ('+84', 'Vietnam'), ('967', 'Yemen'), ('+253', 'Yibuti'), ('+260', 'Zambia'), ('+263', 'Zimbabue')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('pais', models.CharField(choices=[('Afganistán', 'Afganistán'), ('Albania', 'Albania'), ('Alemania', 'Alemania'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua y Barbuda', 'Antigua y Barbuda'), ('Arabia Saudita', 'Arabia Saudita'), ('Argelia', 'Argelia'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaiyán', 'Azerbaiyán'), ('Bahamas', 'Bahamas'), ('Baréin', 'Baréin'), ('Bangladés', 'Bangladés'), ('Barbados', 'Barbados'), ('Belice', 'Belice'), ('Benín', 'Benín'), ('Bielorrusia', 'Bielorrusia'), ('Birmania', 'Birmania'), ('Bolivia', 'Bolivia'), ('Bosnia y Herzegovina', 'Bosnia y Herzegovina'), ('Botsuana', 'Botsuana'), ('Brasil', 'Brasil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Bután', 'Bután'), ('Cabo Verde', 'Cabo Verde'), ('Camboya', 'Camboya'), ('Camerún', 'Camerún'), ('Canadá', 'Canadá'), ('Catar', 'Catar'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Chipre', 'Chipre'), ('Colombia', 'Colombia'), ('Comoras', 'Comoras'), ('Congo (Brazzaville)', 'Congo (Brazzaville)'), ('Congo (Kinshasa)', 'Congo (Kinshasa)'), ('Costa Rica', 'Costa Rica'), ('Croacia', 'Croacia'), ('Cuba', 'Cuba'), ('Dinamarca', 'Dinamarca'), ('Dominica', 'Dominica'), ('Ecuador', 'Ecuador'), ('Egipto', 'Egipto'), ('El Salvador', 'El Salvador'), ('Guinea Ecuatorial', 'Guinea Ecuatorial'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Eswatini', 'Eswatini'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Filipinas', 'Filipinas'), ('Finlandia', 'Finlandia'), ('Fiyi', 'Fiyi'), ('Francia', 'Francia'), ('Gabón', 'Gabón'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Ghana', 'Ghana'), ('Grecia', 'Grecia'), ('Granada', 'Granada'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bisáu', 'Guinea-Bisáu'), ('Guyana', 'Guyana'), ('Haití', 'Haití'), ('Honduras', 'Honduras'), ('Hungría', 'Hungría'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Irán', 'Irán'), ('Irak', 'Irak'), ('Irlanda', 'Irlanda'), ('Islandia', 'Islandia'), ('Israel', 'Israel'), ('Italia', 'Italia'), ('Jamaica', 'Jamaica'), ('Japón', 'Japón'), ('Jordania', 'Jordania'), ('Kazajistán', 'Kazajistán'), ('Kenia', 'Kenia'), ('Kirguistán', 'Kirguistán'), ('Kiribati', 'Kiribati'), ('Kosovo', 'Kosovo'), ('Letonia', 'Letonia'), ('Líbano', 'Líbano'), ('Liberia', 'Liberia'), ('Libia', 'Libia'), ('Liechtenstein', 'Liechtenstein'), ('Lituania', 'Lituania'), ('Luxemburgo', 'Luxemburgo'), ('Madagascar', 'Madagascar'), ('Malasia', 'Malasia'), ('Malawi', 'Malawi'), ('Maldivas', 'Maldivas'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marruecos', 'Marruecos'), ('Mauricio', 'Mauricio'), ('Mauritania', 'Mauritania'), ('México', 'México'), ('Micronesia', 'Micronesia'), ('Moldavia', 'Moldavia'), ('Mónaco', 'Mónaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Nicaragua', 'Nicaragua'), ('Níger', 'Níger'), ('Nigeria', 'Nigeria'), ('Noruega', 'Noruega'), ('Nueva Zelanda', 'Nueva Zelanda'), ('Omán', 'Omán'), ('Pakistán', 'Pakistán'), ('Palau', 'Palau'), ('Panamá', 'Panamá'), ('Papúa Nueva Guinea', 'Papúa Nueva Guinea'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('República Centroafricana', 'República Centroafricana'), ('República Checa', 'República Checa'), ('República del Congo', 'República del Congo'), ('Rumanía', 'Rumanía'), ('Rusia', 'Rusia'), ('Ruanda', 'Ruanda'), ('San Cristóbal y Nieves', 'San Cristóbal y Nieves'), ('Santa Lucía', 'Santa Lucía'), ('San Marino', 'San Marino'), ('Santo Tomé y Príncipe', 'Santo Tomé y Príncipe'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leona', 'Sierra Leona'), ('Singapur', 'Singapur'), ('Siria', 'Siria'), ('Somalia', 'Somalia'), ('Sri Lanka', 'Sri Lanka'), ('Sudán', 'Sudán'), ('Suecia', 'Suecia'), ('Suiza', 'Suiza'), ('Surinam', 'Surinam'), ('Tayikistán', 'Tayikistán'), ('Tailandia', 'Tailandia'), ('Tanzania', 'Tanzania'), ('Timor Oriental', 'Timor Oriental'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad y Tobago', 'Trinidad y Tobago'), ('Túnez', 'Túnez'), ('Turkmenistán', 'Turkmenistán'), ('Turquía', 'Turquía'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ucrania', 'Ucrania'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yibuti', 'Yibuti'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabue', 'Zimbabue')], max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('tipo_usuario', models.CharField(choices=[('aspirante', 'Aspirante'), ('reclutador', 'Reclutador')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_vida', models.FileField(upload_to='hojas_de_vida/')),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('sector_laboral', models.CharField(choices=[('tecnologia_de_la_informacion', 'Tecnologia de la Informacion'), ('finanzas_y_contabilidad', 'Finanzas y Contabilidad'), ('salud', 'Salud'), ('educacion', 'Educacion'), ('ingenieria', 'Ingenieria'), ('marketing_y_publicidad', 'Marketing y Publicidad'), ('ventas', 'Ventas'), ('servicios_al_cliente', 'Servicios al Cliente'), ('construccion', 'Construccion'), ('manufactura', 'Manufactura'), ('recursos_humanos', 'Recursos Humanos'), ('artes_y_entretenimiento', 'Artes y Entretenimiento'), ('turismo_y_hospitalidad', 'Turismo y Hospitalidad'), ('transporte_y_logistica', 'Transporte y Logistica'), ('legal', 'Legal'), ('investigacion_y_desarrollo', 'Investigacion y Desarrollo'), ('energia_y_recursos_naturales', 'Energia y Recursos Naturales'), ('servicios_profesionales', 'Servicios Profesionales'), ('medios_de_comunicacion', 'Medios de Comunicacion'), ('agricultura', 'Agricultura'), ('gobierno_y_administracion_publica', 'Gobierno y Administracion Publica'), ('ciencia_y_tecnologia', 'Ciencia y Tecnologia'), ('servicios_sociales', 'Servicios Sociales'), ('medio_ambiente', 'Medio Ambiente'), ('comercio_y_retail', 'Comercio y Retail')], max_length=50)),
                ('gustos_intereses', models.TextField()),
                ('salario', models.CharField(choices=[('500000-1000000', '500,000 - 1,000,000'), ('1000000-1500000', '1,000,000 - 1,500,000'), ('1500000-2000000', '1,500,000 - 2,000,000'), ('2000000-2500000', '2,000,000 - 2,500,000'), ('2500000-3000000', '2,500,000 - 3,000,000'), ('3000000-3500000', '3,000,000 - 3,500,000'), ('3500000-4000000', '3,500,000 - 4,000,000'), ('4000000-4500000', '4,000,000 - 4,500,000'), ('4500000-5000000', '4,500,000 - 5,000,000'), ('5000000-6000000', '5,000,000 - 6,000,000'), ('6000000-7000000', '6,000,000 - 7,000,000'), ('7000000-8000000', '7,000,000 - 8,000,000'), ('8000000-9000000', '8,000,000 - 9,000,000'), ('9000000-10000000', '9,000,000 - 10,000,000'), ('10000000-12000000', '10,000,000 - 12,000,000'), ('12000000-14000000', '12,000,000 - 14,000,000'), ('14000000-16000000', '14,000,000 - 16,000,000'), ('16000000-18000000', '16,000,000 - 18,000,000'), ('18000000-20000000', '18,000,000 - 20,000,000'), ('20000000+', 'Más de 20,000,000')], max_length=50)),
                ('modalidad_trabajo', models.CharField(choices=[('virtual', 'virtual'), ('presencial', 'presencial'), ('mixto', 'mixto'), ('cualquiera', 'cualquiera')], max_length=50)),
                ('disponibilidad_de_empezar', models.DateField()),
                ('disponibilidad_viajar', models.BooleanField(default=False)),
                ('proyectos', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('competencias_tecnicas', models.TextField()),
                ('habilidades_blandas', models.TextField()),
                ('idioma_natal', models.CharField(choices=[('ingles', 'ingles'), ('espanol', 'espanol'), ('chino', 'chino'), ('frances', 'frances'), ('aleman', 'aleman'), ('portugues', 'portugues'), ('italiano', 'italiano'), ('arabe', 'arabe'), ('japones', 'japones'), ('ruso', 'ruso'), ('holandes', 'holandes'), ('coreano', 'coreano'), ('sueco', 'sueco'), ('turco', 'turco'), ('hindi', 'hindi'), ('hebreo', 'hebreo'), ('polaco', 'polaco'), ('griego', 'griego'), ('checo', 'checo'), ('danes', 'danes')], max_length=20)),
                ('video_presentacion', models.FileField(upload_to='videos_presentacion/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('redes_sociales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.redessociales')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='users.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaAspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('ingles', 'ingles'), ('espanol', 'espanol'), ('chino', 'chino'), ('frances', 'frances'), ('aleman', 'aleman'), ('portugues', 'portugues'), ('italiano', 'italiano'), ('arabe', 'arabe'), ('japones', 'japones'), ('ruso', 'ruso'), ('holandes', 'holandes'), ('coreano', 'coreano'), ('sueco', 'sueco'), ('turco', 'turco'), ('hindi', 'hindi'), ('hebreo', 'hebreo'), ('polaco', 'polaco'), ('griego', 'griego'), ('checo', 'checo'), ('danes', 'danes')], max_length=30)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='users.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Reclutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('NIT', models.CharField(max_length=50)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('cantidad_empleados', models.IntegerField()),
                ('sede_principal', models.CharField(max_length=255)),
                ('registro_camara_comercio', models.FileField(upload_to='registros_camara_comercio/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.representantelegal')),
            ],
        ),
    ]
