# Generated by Django 5.1.1 on 2024-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_idioma_remove_idiomaaspirante_idioma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiomaaspirante',
            name='idiomas',
        ),
        migrations.AddField(
            model_name='idiomaaspirante',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ingles', 'ingles'), ('espanol', 'espanol'), ('chino', 'chino'), ('frances', 'frances'), ('aleman', 'aleman'), ('portugues', 'portugues'), ('italiano', 'italiano'), ('arabe', 'arabe'), ('japones', 'japones'), ('ruso', 'ruso'), ('holandes', 'holandes'), ('coreano', 'coreano'), ('sueco', 'sueco'), ('turco', 'turco'), ('hindi', 'hindi'), ('hebreo', 'hebreo'), ('polaco', 'polaco'), ('griego', 'griego'), ('checo', 'checo'), ('danes', 'danes')], max_length=30, null=True),
        ),
    ]
