# Generated by Django 5.1.1 on 2024-09-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_idiomaaspirante_idiomas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
