# Generated by Django 5.1.1 on 2024-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profile_photos/default_profile.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
