# Generated by Django 5.1.1 on 2024-10-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reclutador_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_puesto', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='users.aspirante')),
            ],
        ),
    ]
