# Generated by Django 5.1.1 on 2024-10-15 17:10

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_experiencialaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='salario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('COP', 'Peso colombiano (COP)'), ('USD', 'Dólar estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Libra esterlina (GBP)'), ('CAD', 'Dólar canadiense (CAD)'), ('AUD', 'Dólar australiano (AUD)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], default='COP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='salario',
            field=djmoney.models.fields.MoneyField(currency_choices=[('COP', 'Peso colombiano (COP)'), ('USD', 'Dólar estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Libra esterlina (GBP)'), ('CAD', 'Dólar canadiense (CAD)'), ('AUD', 'Dólar australiano (AUD)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], decimal_places=2, default_currency='COP', max_digits=14),
        ),
    ]
