# Generated by Django 5.1.1 on 2024-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_aspirante_palabras_clave_aspirante_salario_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='embeddings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
