# Generated by Django 5.1.1 on 2024-10-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_aspirante_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclutador_empresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclutador_empresa',
            name='embeddings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
