# Generated by Django 5.1.1 on 2024-10-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_reclutador_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclutador_empresa',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
