# Generated by Django 5.1.1 on 2024-09-29 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0002_remove_empleo_palabras_clave_alter_empleo_reclutador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPostEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='post_video_empleo/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos_reclutador.empleo')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos_reclutador.empleo')),
                ('VideoPostEmpleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos_reclutador.videopostempleo')),
            ],
            options={
                'unique_together': {('Empleo', 'VideoPostEmpleo')},
            },
        ),
    ]
