# Generated by Django 5.1.1 on 2024-09-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0004_alter_videopostempleo_empleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='palabras_clave',
            field=models.TextField(),
        ),
    ]
