# Generated by Django 5.1.1 on 2024-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0005_alter_empleo_palabras_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='habilidades_blandas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
