# Generated by Django 5.1.1 on 2024-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0006_empleo_habilidades_blandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='embeddings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
