# Generated by Django 5.1.1 on 2024-11-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0008_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='empleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleos_reclutador.empleo'),
        ),
    ]
