# Generated by Django 5.1.1 on 2024-11-05 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos_reclutador', '0009_oferta_empleo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopostempleo',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='videopostempleo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_VideoPostEmpleo', to=settings.AUTH_USER_MODEL),
        ),
    ]
