# Generated by Django 5.1.1 on 2024-10-01 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleos_reclutador', '0005_alter_empleo_palabras_clave'),
        ('users', '0011_reclutador_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aspirante')),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos_reclutador.empleo')),
            ],
        ),
    ]
