# Generated by Django 5.1.1 on 2024-10-01 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_aspirante', '0002_favoritos'),
        ('users', '0011_reclutador_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_post', models.FileField(upload_to='videos_post_aspirante/')),
                ('palabras_clave', models.TextField()),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aspirante')),
            ],
        ),
    ]
