# Generated by Django 5.1.1 on 2024-10-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_aspirante', '0003_crearvideo'),
        ('users', '0011_reclutador_empresa_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearVideo',
            new_name='Video_post',
        ),
    ]
