# Generated by Django 5.1.1 on 2024-10-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_aspirante', '0004_rename_crearvideo_video_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_post',
            name='embeddings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
