# Generated by Django 5.1.1 on 2024-11-05 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_aspirante', '0005_video_post_embeddings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video_post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_VideoPostAspirante', to=settings.AUTH_USER_MODEL),
        ),
    ]
